### ISSUE TITLE
Some match summary pages are not displaying

### ISSUE THREAD

**Issue by Cepheid-UK** [w3champions/website#317] opened 2020-12-21 14:29 UTC
Example:

https://www.w3champions.com/match/5fe09f70e8fc1825175cfb8c

Match history of iDentify#11833 (who reported the issue) seems to have a disproportionate number of these:

https://www.w3champions.com/player/iDentify%2311833/matches

The data appears to be received correctly, maybe an error in the client rendering.

![concealedhill](https://user-images.githubusercontent.com/40397054/102787378-e7530600-4398-11eb-9958-8f7e76cb7e84.PNG)

**Comment by jj-apps** [comment] 2020-12-28 08:43
@Cepheid-UK 
It seems to be only happening for iDentify#11833 in 1v1 flo games where he was the winner.

The error is caused by his battletag being returned from the api without the #number in the playerscores array.

Returns as `'iDentify'`, but should be `iDentify#11833`

**Comment by jj-apps** [comment] 2021-01-20 20:21
@Cepheid-UK Can we close this now?

**Comment by modmoto** [comment] 2021-01-21 08:29
seems fine to me, right? I close it. I you @Cepheid-UK has anything against it, we can reopen =)

Thanks for the fix! @jj-apps

**Closed by modmoto** 2021-01-21 08:29 UTC
Labels: bug
